# Generated by Django 3.2.8 on 2021-10-30 16:06

from django.db import migrations, models
import django.db.models.deletion
import roles.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', roles.fields.DiscordObjectField()),
                ('emoji', roles.fields.DiscordObjectField()),
                ('role', roles.fields.DiscordObjectField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Expiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', roles.fields.DiscordObjectField()),
                ('when', models.DateTimeField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='roles.assignment')),
            ],
        ),
    ]
